

<?php
   //lấy các biến hứng hàm trong Blocks
   	
   	
   	$show=$this->getEnable();
   	
       //$g=$this->getIdCategory();
   	$_productCollection=$this->getProductPrice();
   	
       $_helper = $this->helper('catalog/output');
    ?> 
<?php if($show=="1") :  ?>
<div class="category-products mycustomproduct">
   <?php //$_collectionSize = $_productCollection->count() ?>
   <?php // $_columnCount = $this->getColumnCount(); ?>
   <?php  $_columnCount = 4; ?>
   <div class="title">
      <strong>
         <h2><span><?php echo $this->__('Sách khuyên bạn đọc') ?></span></h2>
      </strong>
   </div>
   <div class="owl-carousel owl-theme">
      <?php $i=0; foreach ($_productCollection  as $_product): ?>
      <?php  $_product = $this->getAllDataProduct($_product->getId())  ; ?>
      <div class="item"
      <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(120); ?>" width="200" height="150" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
      <div class="produc-info" style ="padding-bottom: 88px; min-height: 182px;">
         <h2 class="product-name">
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
            <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
            </a>
         </h2>
         <?php if($_product->getRatingSummary()): ?>
         <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
         <?php endif; ?>
         <?php echo $this->getPriceHtml($_product, true) ?>
         <div class="actions">
            <?php if($_product->isSaleable()): ?>
            <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
            <?php else: ?>
            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
            <?php endif; ?>
            <ul class="add-to-links">
               <?php if ($this->helper('wishlist')->isAllow()) : ?>
               <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
               <?php endif; ?>
               <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
               <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
               <?php endif; ?>
            </ul>
         </div>
      </div>
      <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
   </div>
   <?php endif ?>
   <?php endforeach ?>
   <?php //endforeach ?>
</div>
</div>
<?php elseif($show=="0") : ?>
<?php	echo "module da bi disabale";?>
<?php endif; ?>
<script type="text/javascript">
    jQuery(document).ready(function($) {
        jQuery('.owl-carousel').owlCarousel({
            autoPlay: true, //Set AutoPlay to 3 seconds
            pagination: false,
            navigation: true,

            items: 1,
            stopOnHover: true,
            animateIn: 'slideInUp',
            animateOut: 'slideOutUp',
            slideSpeed: 250,
            itemsDesktop: [1199, 4],
            itemsCustom: 3,
            itemsCustom: [
                [0, 2],
                [400, 1],
                [700, 4],
                [1000, 4],
                [1200, 4],
                [1600, 4]
            ],

            itemsDesktopSmall: [979, 3]
        });
    });
</script>