
<?php
$_helper = $this->helper('catalog/output');
$pslider_id = $this->getGroupId();
$pslider = Mage::getModel('catalog/product')->getCollection();
$pslider->getSelect()->where('cats_id = ?', $pslider_id)->where('status = ?', 1)->order('position asc');

?>
<?php
$i = 0;
foreach ( $pslider as $mtab )  {  
$i++;
$slidewidth=165;
?>
	<div class="title-slider" ><?php echo $mtab->getTitle(); ?></div>
		<div id="owl<?php echo $pslider_id; ?>-<?php echo $i; ?>" class="mst-carousel">			
			<?php foreach ($_productCollection as $_product) { ?>
				<div class="item">
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image" ><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize( $slidewidth ); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
					<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
					<?php     echo $this->getReviewsSummaryHtml($_product, 'short');  ?>
					<?php     echo $this->getPriceHtml($_product, true);  ?>
					<div class="actions">
							<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
						
							<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
						
						<?php } ?>
					
						<ul class="add-to-links">
							<?php if ($this->helper('wishlist')->isAllow()) : ?>
								<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
							<?php endif; ?>
							<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
								<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
							<?php endif; ?>
						</ul>
											
					</div>					
				</div>			
		</div>
<script type="text/javascript">
	jQuery(function($) {
	 $('.mst-carousel').owlCarousel({
	autoPlay: true; //Set AutoPlay to 3 seconds
	items:5;
	pagination:true;
	 navigation : true;
	 stopOnHover:true;
	 slideSpeed:250;
	itemsDesktop : [1199,4],
	itemsCustom:3;
	itemsCustom: [[0, 2], [400, 3], [700, 4], [1000, 5], [1200, 6], [1600, 8]],

	itemsDesktopSmall : [979,3]
	 
	});	
		});
	</script>