 <div class="block-title">
        <strong><h2><span><?php echo $this->__('Các nhà văn trẻ') ?></span></h2></strong>
    </div>
<div class="owl-carousel3 owl-theme">
	
    <div class="item"><img alt="" src=" <?php echo $this->getSkinUrl('images/tacgia_tre/600x325_iris.jpg ') ?>" width="100%" /></div>
    <div class="item"><img alt="" src=" <?php echo $this->getSkinUrl('images/tacgia_tre/600x325_minh-nhat.jpg ') ?>" width="100%" /></div>
	<div class="item"><img alt="" src=" <?php echo $this->getSkinUrl('images/tacgia_tre/600x325_mp3.jpg ') ?>" width="100%" /></div>
    <div class="item"><img alt="" src=" <?php echo $this->getSkinUrl('images/tacgia_tre/600x325_Nha-van-Gao.jpg ') ?>" width="100%" /></div>
    <div class="item"><img alt="" src=" <?php echo $this->getSkinUrl('images/tacgia_tre/600x325_Nha-van-Nguyen-Ngoc-Thach.jpg ') ?>" width="100%" /></div>
    <div class="item"><img alt="" src=" <?php echo $this->getSkinUrl('images/tacgia_tre/600x325_Nha-van-Tue-Nghi.jpg ') ?>" width="100%" /></div>
    <div class="item"><img alt="" src=" <?php echo $this->getSkinUrl('images/tacgia_tre/600x325_phan-y-yen.jpg ') ?>" width="100%" /></div>
    <div class="item"><img alt="" src=" <?php echo $this->getSkinUrl('images/tacgia_tre/600x325_yeah1.jpg ') ?>" width="100%" /></div>
</div>

<script type="text/javascript">
    jQuery(document).ready(function($) {
        jQuery('.owl-carousel3').owlCarousel({
            autoPlay: true, //Set AutoPlay to 3 seconds
            pagination: false,
            navigation: true,

            items: 1,
            stopOnHover: true,
            animateIn: 'slideInUp',
            animateOut: 'slideOutUp',
            slideSpeed: 450,
            itemsDesktop: [1199, 1],
            itemsCustom: 3,
            itemsCustom: [
                [0, 2],
                [400, 1],
                [700, 1],
                [1000, 1],
                [1200, 1],
                [1600, 4]
            ],

            itemsDesktopSmall: [979, 3]
        });
    });
</script>